### ISSUE TITLE
Add Entity-classes.

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#1]
Add all Entity-classes that are used in the project (Item, Book, ...).
Full entity-support not yet required.

**Comment by PjGeeroms** [comment]
Domain classes added, Entity added for Item
Ready for reviewing.

**Comment by Fredjes** [comment]
No default constructor implementations are needed because the default values are never being used. So just keep the default constructor empty (`super()` is ok) because they are required for JPA-support. In `StoryBag` make a `getItems(): ObservableList<Item>`, this way all functionalities of `ObservableList` can be used. `Item` and its subclasses should consist of JavaFX-properties instead of plain fields.

**Comment by PjGeeroms** [comment]
emptied the default constructor
added getter for ObservableList
replaced plain fields to properties with appropriate getters & setters

**Comment by Fredjes** [comment]
Small correction at `Item.damage` and added required libraries, merged to master.
