### ISSUE TITLE
Add new FXML-files

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#12]
Design and add the new GUI using FXML-files.

**Comment by Fredjes** [comment]
Participation of everyone required.

**Comment by PjGeeroms** [comment]
Working on ItemManagement.

**Comment by limnic** [comment]
Pushed to branch issue/12

**Comment by limnic** [comment]
ready for review

**Comment by Fredjes** [comment]
Reviewed and merged.
