### ISSUE TITLE
Item details provider

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#19]
Create a Factory that will create detailviews based on the selected item.

**Comment by PjGeeroms** [comment]
Added the controllers, the factory & most of the bindings.
Need some help on the binding from TextField to ObservableList

**Comment by Fredjes** [comment]
Added code to bind Property's and ObservableLists + an implementation of that for themes. Remember, if you need this again you can use the PropertyListBinding class I created for this purpose.
