### ISSUE TITLE
Add CRUD-support for items

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#2]
Make an ItemRepository that uses JPA to Create, Read, Update and Delete items + basic JPA-infrastructure (JPAUtil).

**Comment by limnic** [comment]
Created the database and properly configured it for further access. Account has all privileges on the schema so it should all work perfectly.
## Access Configuration
**Host:** `bitcode.io`
**Port:** `3306`
**Schema:** `krekelschool`
**Username:** `projecten`
**Password:** ***********

**Comment by limnic** [comment]
JPAUtil has been created and the necessary JPA libraries have been added to the project.

**Comment by limnic** [comment]
Persistence.xml has been created, unit tests were written and branch has been pushed. Ready for inspection.

**Comment by Fredjes** [comment]
ItemRepository should be filled using JPA (you can use the Item.findAll named query).

**Comment by limnic** [comment]
Added functionality so it can update its data from database using the `sync()` method.

**Comment by Fredjes** [comment]
Reviewed and accepted.
