### ISSUE TITLE
Login system

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#20]
The FXML and functionality of the login system.

**Comment by PjGeeroms** [comment]
Added the FXML & Controller for login. 
Added the method for showing the PopOver.
Added the ControlsFX Library

Ready for reviewing @Fredjes

**Comment by Fredjes** [comment]
Reviewed and merged, issue delayed until completion of issue #14 .

**Comment by Fredjes** [comment]
Issue #14 is completed, you can continue.

**Comment by PjGeeroms** [comment]
All features added. 
Dummy popOver added on mainPanel for testing purposes.
Did a quick CSS override for textfields to get rid of graphic bugs.

**Comment by Fredjes** [comment]
Reviewed and merged.
