### ISSUE TITLE
Automatic hiding based on user

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#21]
GUI-components should be hidden or displayed based on the user that is using the system.

**Comment by limnic** [comment]
User rights are partially implemented into the GUI but still needs some work before review.

**Comment by limnic** [comment]
Nearly ready for review, help needed with a strange FXML bug. @FXML does not fill in the correct variable 'btnDelete' in ItemManagementListItem.java

**Comment by Fredjes** [comment]
Bug fixed and reviewed.
