### ISSUE TITLE
GUI cleanup

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#25]
Clean up the ItemManagement GUI.

**Comment by limnic** [comment]
Ready for review

**Comment by Fredjes** [comment]
Small bug should be fixed, tiles in titlebar and main menu don't match when logged in as administrator: http://prntscr.com/6jucne.

**Comment by limnic** [comment]
Bug fixed and once again ready for review.

**Comment by Fredjes** [comment]
Reviewed and merged.
