### ISSUE TITLE
Implement requests done during sprint demo

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#28]
Implement password-validation, so that a new password satisfies domain rules. Fix a bug where the detailview remains on screen after logout. Implement item copy color codes. Add a magnifying glass to the search textfield.

**Comment by limnic** [comment]
Ready for review (copy color codes should be reviewed later)

**Comment by Fredjes** [comment]
Reviewed and merged.

**Comment by limnic** [comment]
Color codes implemented directly into master branch.

**Comment by Fredjes** [comment]
Reviewed.
