### ISSUE TITLE
Book lookup support

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#33]
Implementation that searches for books online, to automatically fill in all data (Google API).

**Comment by PjGeeroms** [comment]
Can't seem to fix the problem with saving the Image. Anyone an idea?

**Comment by Fredjes** [comment]
I'll take a look.

**Comment by Fredjes** [comment]
I have made some fixes and allowed asynchronous search (already pushed, so pull please), yet I can't seem to reproduce the Image saving problem. What are the steps to reproduce this?

**Comment by PjGeeroms** [comment]
@Fredjes 
When looking up a book with isbn/title like for example: "nooitgenoeg", "harry potter"
it'll load all the books, but when clicking on the save button the error occurs. 
The error is somewhere in the method getImage() that is called when saving to the database. 
I get a NullPointerException in that method. No idea why :(

**Comment by Fredjes** [comment]
Fixed, reviewed and merged with master.

**Comment by PjGeeroms** [comment]
Implementation of the menu to easily select a book
