### ISSUE TITLE
Sprint review changes

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#46]
Implement the changes requested during the sprint review.

**Comment by PjGeeroms** [comment]
Icons added to all the buttons. 
Icons also added in the IconConfig for further use. 
Css edited to support icons
FXMLs edited to support icons

Waiting for database fix to add icons to popup menus

**Comment by Fredjes** [comment]
Merged with master.

**Comment by PjGeeroms** [comment]
Pushed & ready for review? @Fredjes
