### ISSUE TITLE
New Book Search GUI

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#47]
Create a new Book search GUI in case there are multiple results.

**Comment by PjGeeroms** [comment]
Updated the Book Search GUI using custom listItems (using Cache).
Fixed minor bug: "searching books when search field is empty"

Ready for review. @Fredjes

**Comment by PjGeeroms** [comment]
JavaDoc added.

**Comment by Fredjes** [comment]
Reviewed, small edits and merged with master.
