### ISSUE TITLE
Delete item

### ISSUE THREAD

**Issue by Fredjes** [Fredjes/Projecten-2#6]
A confirmation dialog when an item is being deleted. Should consist of:
* OK-button;
* Cancel-button;
* A detailed overview of the item being deleted.

**Comment by limnic** [comment]
Delete item + confirmation dialog has been implemented. One bug with selection left. When selecting an item it sometimes finds no related item copies even when there are. After this bug has been fixed it is ready for review.

**Comment by Fredjes** [comment]
Bug fixed.
